Background article
Nanostring-Biostats/CosMx-Analysis-Scratch-Space pull request #100
Opened 2024-08-21 22:26 UTC by patrickjdanaher

2024-08-21 22:27 UTC, patrickjdanaher commented
@dan11mcguire please especially check correctness of the arguments,

2024-08-23 01:13 UTC, lidanwu requested changes
@patrickjdanaher The content looks fine to me but the format, some terminologies, and description seems problematic and misleading. Please see my comments above and it would be good to get feedbacks from CX regarding this before publishing first.

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +knitr::include_graphics("./figures/exampleheatmap.png")
This figure does NOT exist.

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +CosMx data includes off-target “background” counts appearing randomly at a low frequency across the dataset. In this article, we’ll discuss how background impacts data analysis. Many details follow,
I would put this differently. For example, CosMx data contains non-zero level of background counts from off-target probe binding.

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +2.	For analyses of single cell profiles, for example cell typing or UMAP projections, background contributes a small amount of noise/error. But by far the major driver of noise in single cell profile
recommend to say "readout sparsity",

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +3.	Analyses of single genes in single cells, for example calling cells as +/- for a marker gene, perform poorly regardless of background levels, save for perhaps the top ~10% expressing genes. We rec
typo for "save". not really sure what this sentence is supposed to mean. Do you mean there are 10% of cells expressing that gene?

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +Note: For details of the origins of background counts, see Appendix 1.
please add hyperlink for appendix 1 cited here.

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +Note: This document focuses on background. But always worth bearing in mind is that segmentation errors have a far more deleterious impact on data quality. See Appendix 2 for a brief discussion.
please add hyperlink for appendix 2 cited here. You can do make those appendix files as section in `{#alias}` and then cite the section using `@alias`. See example [here](https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space/blob/Main/posts/napari-cosmx-basics/using-napari-cosmx.qmd#L81).

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +## Introduction
This whole post showed wrong format upon render with limited line breaks and lack of bold fonts for section titles. Most of the issues are due to lack of space after `##`. I have fixed that in my latest commit. Please fix the remaining format issue. 
Below is the rendering before my commit. 
![image](https://github.com/user-attachments/assets/28bdab6f-6d4d-4d31-9031-19bc64381688)

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +From Figure 1, we see that datasets with more signal tend to also have more background, but that background does not rise as quickly as signal. For a nuanced discussion of how background behaves with
I found the term "signal" vs. " background" confusing, you may want to explicitly says that those are the raw count for different types of probes, something like gene-targeting readout vs. non-targetting background readout.

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +```{r, out.width="20%", out.height="20%"}
20% output is too small to see upon render. I have changed to 100% for display in my latest commits for all figures.

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +CosMx datasets tend to be large, containing hundreds of thousands of cells in total, and at least thousands of cells from most individual cell types. When we’re calculating summary statistics, for ex
The sentences don't flow well with me.. I would suggest the following.

> The sample size of CosMx datasets tend to be large, *, with at least *. When *, such as for the purpose of performing DE or *.

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +To demonstrate what statistical theory assures us, we’ll simulate CosMx data for which we can attribute each count to real RNA or background. Our simulation is simple: using a CosMx dataset, we’ll a
we’ll "**assign**" a gene for which only a very small percentage of counts are background, "**simulating**" one of highest expressers.

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +The spatial pattern of this gene’s expression is equally clear with and without background. This example serves to demonstrate a general principle: since background occurs randomly, it does little to
It feels wrong to say 86% of counts are **from** background, we don't know that in the real dataset. It might be good to leave out that sentences and only say "1.16-fold above background".

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> + 	Estimate	Lower 95% conf interval	Upper 95% conf interval	p-value
wrong table format, see [this link ](https://quarto.org/docs/authoring/tables.html)for correct formatting.

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +Now let’s see how background impacts hard statistics. Using the same simulation, we’ll perform a differential expression analysis of how fibroblast cells modulate COL1A1 across the span of the tissue
I'm not really sure what's happening here. This is a t-test on single-cell expression profiles in top vs. bottom halves, right? Is the intention to check the impact of background on spatial pattern detection? If yes, you may want to explicitly say that and mentioned COL1A1 (as shown in figure 2) has different spatial pattern in top vs. bottom halves of the tissues, the down-sampling +/- simulated background does not alter the detection sensitivity of this spatial trend.

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +Now, instead of analyzing one gene over many cells, we’ll see what happens when we analyze all the genes in a single cell. For this, we’ll need a new simulation. We first define a “true” expression p
The description of simulation is confusing here. To my understanding, the sampling probabilities would be from the "true" profiles but only for the gene in 6k gene panel. The current description seems to say the probabilities is given by 6k panel. It might be more straightforward to say 

`Focus on genes present in 6k panel, we sample from a multinomial distribution with probabilities proportional to the gene's abundance in our “true” profile for N times and N equal to 590, the average per-cell non-background count level in a typical 6k dataset.`

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +These simulation settings mimic a middle-of-the-road 6k dataset selected from the datasets in Figure 1, with an expected 698 counts per cell, of which 15.5% are background. Simulating a single cell u
again we don't know the actual background level from real dataset, would be better to say 

> the datasets in Figure 1, with an expected 698 counts per cell, where the observed background level is at 15.5% of expected per cell count.

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +___Figure 5. Simulated single-cell profile for a cell with 589 real counts, with and without an additional 87 background counts, in linear and log-scale. (For log-scale plots, zeroes have been rounde
in linear **(top row)** and log-scale **(bottom row)**

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +The simulated “observed” profiles with and without background are comparably faithful to the ground truth. In other words, background contributes little to the error.
Since the correlation is poor at log scale, it doesn't seem right to say "comparably faithful to the ground truth". It makes more sense to say "exhibited similar correlation to the ground truth".

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +To see how sparsity drives error, we can re-run our simulation for a cell with 20,000 RNA counts:
better to explicitly say "with background" and include it in the y axis title to be consistent with Figure 5.

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +In analyses of this sort, e.g. trying to declare a cell as +/- for a marker gene, background does act as a headwind. If we see 1 count of a gene in a cell, the existence of background means we cannot
If we **observed only** 1 count for a given gene in a cell, * that gene is truly **expressed** in the query cell.

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +___Figure 7. performance metrics for calling cells as +/- for a gene.___
The letter identifiers for subplots are missing in figure 7.

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +___b-d:___ _The true positive rate for cells called positive for a gene vs. expected expression level. Curves are shown for two count thresholds and for typical background (0.02 counts/plex/cell) and
The true positive rate for cells called positive for a gene vs. expected **per cell** expression level **of the given gene**.

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +From Figure 7, we get a broad picture of the performance of calling marker gene positivity. Panel (a) conveys a few important if unsurprising lessons. First, sensitivity rises with expression level;
The publication citation `circa 2024` does NOT work. You need to add the paper in [references.bib](https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space/blob/Main/references.bib) and then cite it with `@alias`. See[ this post ](https://github.com/Nanostring-Biostats/CosMx-Analysis-Scratch-Space/blob/Main/posts/squidpy-essentials/squidpy-essentials.qmd#L45)for example.

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +Note: keep in mind that prevalence can be contextual: a tiny proportion of all cells may be FOXP3+, but looking within T-cells, FOXP3 positivity could reach 10%. Thus by looking for gene positivity w
Could be good to give example application of "improved detection performance in subset of cells" here. Or say that `in the example below, we take advantage of the contextual prevalence for improved detection of rare cell population. `

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +There is a powerful countermeasure to this limitation, described [here](https://nanostring-biostats.github.io/CosMx-Analysis-Scratch-Space/posts/marker-gene-smoothing/){target="_blank"}. To summarize
would be good to call out **expression** neighbors explicitly.

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +In summary, regardless of background level, analyses of single genes in single cells (e.g. of marker genes) have low sensitivity save for high expressing genes. Background increases the false positiv
I guess you mean "except for" instead of "save for".

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +First, in “FalseCode” style background, fluorescent spots from reporter probes can be misconstrued as a gene’s barcode. This kind of background is very rare, on the order of 0.005 counts per plex per
*, in “FalseCode” style background, fluorescent spots from reporter probes **can colocalize with each other in space by random chance and then** be misconstrued as a gene's barcode. * This kind of background can be measured with our **FalseCode controls, which are barcodes with no corresponding probes in hybridization reaction.**

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +Second, in “NegProbe” style background, a hybridization probe binds to the wrong target, then is correctly detected through reporter probes. This is the dominant form of background, occurring at 0.01
“NegProbe” controls.

2024-08-23 01:13 UTC, lidanwu commented on posts/background/index.qmd
> +As a first-order approximation, negprobe-style background happens with equal probability to all genes. (Beyond the first-order view, we have observed small subsets of negprobes with elevated backgrou
Areas of necrosis will generate higher background of "NegProbes", **likely due to more charged and thus sticky surface for nuclei acid probes.**

2024-08-23 22:10 UTC, patrickjdanaher commented on posts/background/index.qmd
> +knitr::include_graphics("./figures/exampleheatmap.png")
good catch.

2024-08-23 22:13 UTC, patrickjdanaher commented on posts/background/index.qmd
> +3.	Analyses of single genes in single cells, for example calling cells as +/- for a marker gene, perform poorly regardless of background levels, save for perhaps the top ~10% expressing genes. We rec
clarified

2024-08-23 22:14 UTC, patrickjdanaher commented on posts/background/index.qmd
> +There is a powerful countermeasure to this limitation, described [here](https://nanostring-biostats.github.io/CosMx-Analysis-Scratch-Space/posts/marker-gene-smoothing/){target="_blank"}. To summarize
I like it

2024-08-23 22:16 UTC, patrickjdanaher commented on posts/background/index.qmd
> +First, in “FalseCode” style background, fluorescent spots from reporter probes can be misconstrued as a gene’s barcode. This kind of background is very rare, on the order of 0.005 counts per plex per
like it

2024-08-23 22:30 UTC, patrickjdanaher commented on posts/background/index.qmd
> +```{r, out.width="20%", out.height="20%"}
thanks!

2024-08-23 22:32 UTC, patrickjdanaher commented on posts/background/index.qmd
> +CosMx datasets tend to be large, containing hundreds of thousands of cells in total, and at least thousands of cells from most individual cell types. When we’re calculating summary statistics, for ex
rewritten

2024-08-23 22:46 UTC, patrickjdanaher commented on posts/background/index.qmd
> +Now let’s see how background impacts hard statistics. Using the same simulation, we’ll perform a differential expression analysis of how fibroblast cells modulate COL1A1 across the span of the tissue
clarified

2024-08-23 22:49 UTC, patrickjdanaher commented on posts/background/index.qmd
> +Now, instead of analyzing one gene over many cells, we’ll see what happens when we analyze all the genes in a single cell. For this, we’ll need a new simulation. We first define a “true” expression p
clarified

2024-08-23 22:50 UTC, patrickjdanaher commented on posts/background/index.qmd
> +These simulation settings mimic a middle-of-the-road 6k dataset selected from the datasets in Figure 1, with an expected 698 counts per cell, of which 15.5% are background. Simulating a single cell u
I'm simulating to exactly 15.5%, so I think it's accurate in this case.

2024-08-23 23:00 UTC, patrickjdanaher commented on posts/background/index.qmd
> +From Figure 7, we get a broad picture of the performance of calling marker gene positivity. Panel (a) conveys a few important if unsurprising lessons. First, sensitivity rises with expression level;
ha - I mean "time periods of approximately 2024". I'll reword.

2024-08-23 23:01 UTC, merged